version: '3.8'

services:
  kogase-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=kogase;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - kogase-network
    labels:
      - "com.kogase.description=Game Telemetry and Analytics Platform"
      - "com.kogase.documentation=http://localhost:8080 (API Documentation)"

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kogase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kogase-network

networks:
  kogase-network:
    driver: bridge

volumes:
  postgres-data: 